site_shop/siteApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('edit_order/<int:order_id>/', OrderEditView.as_view(), name='edit_order'),
    path('cancel-order/<int:order_id>/', CancelOrderView.as_view(), name='cancel_order'),
    path('product/<int:product_id>/review/', ReviewCreateView.as_view(), name='create_review'),
    path('add-to-cart/<int:product_id>/', AddToCartView.as_view(), name='add_to_cart'),
    path('cart/remove/<int:item_id>/', RemoveFromCartView.as_view(), name='remove_from_cart'),
    path('cart/change-quantity/<int:item_id>/', ChangeCartItemQuantityView.as_view(), name='change_quantity'),
    path('cart/clear/', ClearCartView.as_view(), name='clear_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('create_order/', CreateOrderView.as_view(), name='create_order'),
]

site_shop/site_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from .urls import *


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('siteApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

site_shop/siteApp/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator


class Person(AbstractUser):
    first_name = models.CharField(max_length=50, verbose_name="Имя")
    last_name = models.CharField(max_length=50, verbose_name="Фамилия")
    phone = models.CharField(max_length=255, blank=True, null=True, unique=True, verbose_name="Номер телефона")
    email = models.EmailField(verbose_name="Почта")
    role = models.CharField(max_length=1, choices=[('C', 'Client'), ('S', 'Staff')], verbose_name="Роль")

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def has_reviewed(self, product):
        return Feedback.objects.filter(person=self, product=product).exists()

    def get_review_rating(self, product):
        review = Feedback.objects.filter(person=self, product=product).first()
        return review.rating if review else None


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Категория')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, validators=[MinValueValidator(1)], verbose_name="Цена")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    description = models.TextField(blank=True, verbose_name='Информация о услуге')
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name='Фото')
    is_active = models.BooleanField(default=True, verbose_name='Наличие')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Feedback(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    person = models.ForeignKey(Person, on_delete=models.CASCADE, verbose_name='Пользователь')
    comment = models.TextField(verbose_name='Комментарий')
    rating = models.IntegerField(validators=[MaxValueValidator(5)], verbose_name='Оценка')

    def __str__(self):
        return f"Отзыв с рейтингом {self.rating} на товар '{self.product}'"

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class Discounts(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    discount_rate = models.FloatField(verbose_name='Размер скидки')
    start_date = models.DateTimeField(verbose_name='Начало скидки')
    end_date = models.DateTimeField(verbose_name='Конец скидки')

    def __str__(self):
        return f"Скидка на {self.product}"

    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'


class Order(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE, verbose_name='Пользователь')
    products = models.ManyToManyField(Product, verbose_name='Товары')
    close_date = models.DateTimeField(verbose_name='Дата заказа', auto_now_add=True)
    order_date = models.DateTimeField(verbose_name='Дата доставки')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Стоимость')
    delivery_address = models.TextField(verbose_name='Адрес Доставки')
    status = models.BooleanField(default=False, verbose_name='Статус Заказа')

    def __str__(self):
        # Получаем названия первых нескольких товаров в заказе
        product_names = [product.title for product in self.products.all()[:3]]
        product_str = ', '.join(product_names)

        # Если товаров больше, чем отображаем, добавляем многоточие
        if self.products.count() > 3:
            product_str += '...'

        return f"Заказ ({product_str})"

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items', verbose_name='Заказ')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.IntegerField(default=1, verbose_name='Количество')

    def __str__(self):
        return f"{self.product.title} ({self.quantity}) в заказе {self.order.id}"

    class Meta:
        verbose_name = 'Элемент заказа'
        verbose_name_plural = 'Элементы заказов'


class Inventory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.IntegerField(verbose_name='Количество')

    def __str__(self):
        return f"Запасы {self.product}"

    class Meta:
        verbose_name = 'Инвентарь'
        verbose_name_plural = 'Инвентарь'


class CartItem(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.product.title} ({self.quantity})"

    class Meta:
        verbose_name = 'Товар корзины'
        verbose_name_plural = 'Товары корзины'

    def total_price(self):
        return self.quantity * self.product.price


class Cart(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItem)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return f"Корзина пользователя {self.person.username}"

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'

    def update_total_price(self):
        total = 0
        for item in self.items.all():
            total += item.product.price * item.quantity
        self.total_price = total
        self.save()

site_shop/siteApp/views.py
import json
from collections import Counter
from datetime import timedelta
from itertools import combinations

from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import TemplateView, CreateView, UpdateView

from .forms import RegisterUserForm, LoginUserForm
from .models import Product, Order, Person, Feedback, Category, Cart, CartItem, Inventory, OrderItem
from django.db.models import Count


class IndexView(TemplateView):
    template_name = 'siteApp/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Проверка и обновление статусов заказов
        current_time = timezone.now()
        orders_to_update = Order.objects.filter(order_date__lt=current_time, status=False)
        for order in orders_to_update:
            order.status = True  # Устанавливаем статус "Доставлено"
            order.save()

        # Обновление статуса наличия товаров
        Product.objects.filter(inventory__quantity=0).update(is_active=False)
        Product.objects.filter(inventory__quantity__gt=0, is_active=False).update(is_active=True)

        # Получаем продукты с их количеством заказов
        products_ordered_count = Product.objects.annotate(
            orders_count=Count('order')
        ).order_by('-orders_count')

        if self.request.user.is_authenticated:
            cart = Cart.objects.filter(person=self.request.user).first()
            if cart:
                context['cart_items'] = [item.product.id for item in cart.items.all()]
            else:
                context['cart_items'] = []
        else:
            context['cart_items'] = []

        context['popular_products'] = products_ordered_count[:8]

        latest_feedbacks = Feedback.objects.select_related('product', 'person').order_by('-id')[:3]
        context['latest_feedbacks'] = latest_feedbacks
        return context


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'siteApp/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Регистрация"
        return context

    def form_valid(self, form):
        user = form.save(commit=False)  # сохраняем пользователя, но пока без коммита в БД
        user.set_password(form.cleaned_data['password1'])  # устанавливаем и хешируем пароль
        user.save()  # сохраняем пользователя в БД
        login(self.request, user)  # авторизуем пользователя
        print("Регистрация прошла успешно. Добро пожаловать!")
        return redirect('home')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'siteApp/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Авторизация"
        return context

    def get_success_url(self):
        return reverse_lazy('home')


class ProductListView(TemplateView):
    template_name = 'siteApp/product_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получаем список всех категорий
        categories = Category.objects.all()
        context['categories'] = categories

        category_id = self.request.GET.get('category')
        search_query = self.request.GET.get('search')
        availability = self.request.GET.get('availability')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')
        reset_filters = self.request.GET.get('reset_filters')

        apply_filters = self.request.GET.get('apply_filters')
        if apply_filters:
            # Сбрасываем значения min_price и max_price
            context['min_price'] = None
            context['max_price'] = None
        else:
            # Сохраняем текущие значения для отображения в форме
            context['min_price'] = self.request.GET.get('min_price')
            context['max_price'] = self.request.GET.get('max_price')

        products = Product.objects.all()

        if reset_filters:
            # Сброс всех фильтров, кроме фильтра категории
            products = Product.objects.filter(category_id=category_id)
        else:
            # Приоритет у поискового запроса
            if search_query:
                products = products.filter(title__icontains=search_query)
            elif category_id:
                products = products.filter(category_id=category_id)
            elif not category_id and categories.exists():
                # Если категория не выбрана, используем первую доступную
                products = products.filter(category_id=categories.first().id)

            # Применение остальных фильтров
            if availability != "" and availability is not None:
                products = products.filter(is_active=availability == "1")
            if min_price:
                products = products.filter(price__gte=min_price)
            if max_price:
                products = products.filter(price__lte=max_price)

        if self.request.user.is_authenticated:
            cart = Cart.objects.filter(person=self.request.user).first()
            if cart:
                context['cart_items'] = [item.product.id for item in cart.items.all()]
            else:
                context['cart_items'] = []
        else:
            context['cart_items'] = []

        context['products'] = products
        return context


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'siteApp/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Получаем информацию о текущем пользователе
        user = get_object_or_404(Person, username=self.request.user.username)
        context['user'] = user

        # Получаем заказы пользователя
        orders = Order.objects.filter(person=user).order_by('-order_date')
        for order in orders:
            # Расчет времени до доставки
            time_left = order.order_date - timezone.now()
            # Проверка, остался ли меньше часа до доставки
            order.can_modify = time_left > timedelta(hours=1)

            product_reviews = {}
            for product in order.products.all():
                has_review = Feedback.objects.filter(person=user, product=product).exists()
                review_rating = Feedback.objects.filter(person=user,
                                                        product=product).first().rating if has_review else None
                product_reviews[product.id] = {'has_review': has_review, 'review_rating': review_rating}

            # Добавляем словарь к объекту заказа
            order.product_reviews = product_reviews

        context['orders'] = orders
        return context


class OrderEditView(View):
    def post(self, request, order_id):
        order = get_object_or_404(Order, id=order_id, person=request.user, status=False)
        order.delivery_address = request.POST.get('delivery_address')
        order.order_date = request.POST.get('order_date')
        order.save()
        return redirect('profile')


class CancelOrderView(LoginRequiredMixin, View):
    def post(self, request, order_id):
        order = get_object_or_404(Order, id=order_id, person=request.user)

        if not order.status:
            # Перебор всех элементов заказа и возврат товаров на склад
            for item in order.order_items.all():
                inventory_item = Inventory.objects.get(product=item.product)
                inventory_item.quantity += item.quantity
                inventory_item.save()

            # Удаление заказа
            order.delete()

        return redirect('profile')


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Feedback
    fields = ['rating', 'comment']
    template_name = 'siteApp/review.html'

    def form_valid(self, form):
        form.instance.person = self.request.user
        form.instance.product = get_object_or_404(Product, pk=self.kwargs['product_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('profile')


class AddToCartView(View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        product_id = data.get('product_id')
        product = get_object_or_404(Product, id=product_id)
        cart, _ = Cart.objects.get_or_create(person=request.user)
        cart_item, created = CartItem.objects.get_or_create(
            person=request.user,
            product=product
        )
        if created:
            cart.items.add(cart_item)
        cart.update_total_price()

        return JsonResponse({'status': 'success'})


class CartView(LoginRequiredMixin, TemplateView):
    template_name = 'siteApp/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart, _ = Cart.objects.get_or_create(person=self.request.user)
        context['cart'] = cart
        return context


class RemoveFromCartView(View):
    def post(self, request, item_id):
        cart_item = get_object_or_404(CartItem, id=item_id, person=request.user)
        cart = Cart.objects.get(person=request.user)
        cart.items.remove(cart_item)
        cart_item.delete()
        # Пересчитать общую стоимость корзины
        cart.total_price = sum(item.product.price * item.quantity for item in cart.items.all())
        cart.save()
        return redirect('cart')


class ChangeCartItemQuantityView(View):
    def post(self, request, item_id):

site_shop/siteApp/templates/siteApp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link type="text/css" href="{% static 'siteApp/css/admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>{{title}}</title>
    <meta name="csrf-token" content="{{ csrf_token }}">
</head>
<body>
    <header class="border-bottom">
        <nav class="navbar navbar-expand-lg navbar-light bg-light me-5 ms-5">
          <div class="container-fluid">
             <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
             </button>
            <div class="collapse navbar-collapse ms-5 me-5" id="navbarText">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'home' %}">Главная</a>
                </li>
                <li class="nav-item ms-2 me-2">
                  <a class="nav-link" href="{% url 'product_list' %}" role="button" aria-expanded="false">
                    Ассортимент товаров
                  </a>
                </li>
                  {% if request.user.is_authenticated %}
                    <li class="nav-item ms-2 me-2">
                      <a class="nav-link" href="{% url 'cart' %}" role="button" aria-expanded="false">
                        Корзина
                      </a>
                    </li>
                  {% endif %}
                  {% if request.user.is_superuser %}
                    <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="/admin">Admin-панель</a>
                    </li>
                  {% endif %}
              </ul>
              <span class="navbar-text">
                {% if request.user.is_authenticated %}
                    <li class="list-group-item last d-flex "><a class="opacity-75 nav-link me-2" href="{% url 'profile' %}">  {{user.username}} </a> | <a class="nav-link ms-1" href="{% url 'logout' %}">Выйти</a></li>
                {% else %}
                    <li class="list-group-item last d-flex"><a class="nav-link me-2" href="{% url 'register' %}">Регистрация</a> | <a class="nav-link ms-2" href="{% url 'login' %}">Войти</a></li>
                {% endif %}
              </span>
            </div>
          </div>
        </nav>
    </header>
    <main class="">
        {% block content %}
		{% endblock %}
    </main>
    <footer class="text-center text-lg-start bg-light text-muted">
        <section class="mt-4 border-top">
        <div class="container text-center text-md-start mt-5">
          <div class="row mt-3 text-center">
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
              <h6 class="text-uppercase fw-bold mb-4">
                <i class="fas fa-gem me-3"></i>Flowers-Donbass
              </h6>
              <p class="ms-3">
                Здесь вы можете узнать больше перейдя на следующие ссылки
              </p>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
              <h6 class="text-uppercase fw-bold mb-4">
                Полезные ссылки
              </h6>
              <p>
                <a href="#!" class="text-reset">О нас</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Права</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Записи</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Помощь</a>
              </p>
            </div>
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <h6 class="text-uppercase fw-bold mb-4 ms-3">Контакты</h6>
              <p><i class="fas fa-home me-3"></i> Донецк, ул. Артёма 111</p>
              <p>
                <i class="fas fa-envelope me-3"></i>
                flowers@mail.ru
              </p>
              <p><i class="fas fa-phone me-3"></i> + 7 949 --- -- --</p>
              <p><i class="fas fa-print me-3"></i> + 7 949 --- -- --</p>
            </div>
          </div>
        </div>
        </section>

        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2023
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'siteApp/js/add_cart.js' %}"></script>
    <script type="text/javascript" src="{% static 'siteApp/js/cart_ajax.js' %}"></script>
</body>
</html>

site_shop/siteApp/templates/siteApp/create_order.html
{% extends 'siteApp/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <h2 class="mb-4">Оформление заказа</h2>
    <div class="row">
        <div class="col-md-6">
            <h4>Товары в заказе</h4>
            <ul class="list-group mb-3">
                {% for item in cart.items.all %}
                <li class="list-group-item d-flex align-items-center">
                    <img src="{{ item.product.photo.url }}" alt="{{ item.product.title }}" class="img-fluid me-3" style="width: 60px; height: auto;">
                    <div class="flex-grow-1">
                        <h5>{{ item.product.title }}</h5>
                        <p>Количество: {{ item.quantity }}</p>
                        <p>Цена: {{ item.product.price }} руб.</p>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <h5 class="text-end">Итоговая стоимость: {{ cart.total_price }} руб.</h5>
        </div>

        <div class="col-md-6">
            <form method="post" class="card p-4">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="address" class="form-label">Адрес доставки:</label>
                    <input type="text" class="form-control" name="address" required>
                </div>
                <div class="mb-3">
                    <label for="delivery_time" class="form-label">Время доставки:</label>
                    <input type="datetime-local" class="form-control" name="delivery_time" required>
                </div>
                <button type="submit" class="btn btn-warning">Оформить заказ</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

site_shop/siteApp/templates/siteApp/index.html
{% extends 'siteApp/base.html' %}
{% load custom_filters %}

{% block content %}
    <div class="text-center welcome-block">
        <h1>Добро пожаловать в наш интернет-магазин цветов!</h1>
        <p>Здесь вы найдете лучший ассортимент цветов и букетов для любого случая.</p>
    </div>

    <section class="container mt-5 mb-5">
        <h2>Популярные товары</h2>

        <div class="row">
        {% for product in popular_products %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-12 mt-4">
                <div class="card " style="height: 100%;">
                  <img src="{{ product.photo.url }}" type="button" class="card-img-top" alt="{{ product.title }}" style="height: 200px; object-fit: cover;"  data-bs-toggle="modal" data-bs-target="#productModal{{ product.id }}">
                  <div class="card-body">
                    <h5 class="card-title">{{ product.title }}</h5>
                      <div class="d-flex justify-content-between align-items-baseline">
                        <p class="card-text mb-3 mt-2">Цена: {{ product.price }} руб.</p>
                        {% if product.is_active %}
                          {% if user.is_authenticated %}
                            {% if product.id in cart_items %}
                                <button class="btn btn-secondary disabled">Уже в корзине</button>
                            {% else %}
                                <button type="button" class="btn btn-primary" data-product-id="{{ product.id }}" onclick="addToCart(this, {{ product.id }})">В корзину</button>
                            {% endif %}
                          {% else %}
                            <a class="text-success" href="{% url 'login' %}">Войти для заказа</a>
                          {% endif %}
                        {% endif %}
                      </div>
                      <p class="card-text">
                        {% if product.is_active %}
                            <span class="text-success">Есть в наличии</span>
                        {% else %}
                            <span class="text-danger">Нет в наличии</span>
                        {% endif %}
                    </p>
                  </div>

                </div>
            </div>
        {% endfor %}
        </div>

        <!-- Модальные окна для товара -->
        {% for product in popular_products %}
        <div class="modal fade" id="productModal{{ product.id }}" tabindex="-1" aria-labelledby="productModalLabel{{ product.id }}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg"> <!-- Изменено на modal-lg для большего размера -->
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="productModalLabel{{ product.id }}">{{ product.title }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body row">
                        <div class="col-md-6 text-center">
                            <!-- Фиксированный размер картинки -->
                            <img src="{{ product.photo.url }}" class="img-fluid" alt="{{ product.title }}" style="height: 300px; object-fit: cover;">
                        </div>
                        <div class="col-md-6">
                            <p><span class="fw-bold">Описание: </span>{{ product.description }}</p>
                            <p class="card-text mb-3 mt-2"><span class="fw-bold">Цена: </span>{{ product.price }} руб.</p>
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        {% if product.is_active %}
                            <span class="text-success">Есть в наличии</span>
                            {% if user.is_authenticated %}
                                {% if product.id in cart_items %}
                                    <button class="btn btn-secondary disabled">Уже в корзине</button>
                                {% else %}
                                    <form method="post" action="{% url 'add_to_cart' product.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-primary">В корзину</button>
                                    </form>
                                {% endif %}
                            {% else %}
                                <a class="text-success" href="{% url 'login' %}">Войти для заказа</a>
                            {% endif %}
                        {% else %}
                            <span class="text-danger">Нет в наличии</span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </section>

    <div class="container mt-5 mb-5">
        <h2>Отзывы довольных клиентов</h2>
        <div class="row">
            {% for feedback in latest_feedbacks %}
                <div class="col-lg-4 col-md-6 mt-4">
                    <div class="card" style="height: 100%;">
                        <img src="{{ feedback.product.photo.url }}" class="card-img-top" alt="{{ feedback.product.title }}" style="height: 250px; object-fit: cover;">
                        <div class="card-body">
                            <h5 class="card-title">{{ feedback.product.title }}</h5>
                            <p class="card-text m-0">{{ feedback.comment }}</p>
                            <div class="rating-index">
                                {% for star in 1|to:6 %}
                                    <span class="{% if star <= feedback.rating %}filled-star{% else %}empty-star{% endif %}" id="{{ star }}">★</span>
                                {% endfor %}
                            </div>
                            <div class="blockquote-footer m-0">
                                {{ feedback.person.first_name }} <cite title="Дата доставки">{{ feedback.product.order_set.first.order_date|date:"Y-m-d" }}</cite>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

site_shop/siteApp/templates/siteApp/login.html
{% extends 'siteApp/base.html' %}

{% block content %}
<div class="mt-5 mb-5 pt-5 pb-5">
    <h1 class="text-center mb-4">{{title}}</h1>

    <form method="post" class="text-center">
        {% csrf_token %}

        <div class="form-error text-danger">{{ form.non_field_errors }}</div>

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
            <div class="form-error text-danger">{{ f.errors }}</div>
        {% endfor %}

        <button type="submit" class="btn btn-secondary bg-light text-dark">Войти</button>
    </form>
</div>

{% endblock %}